### ISSUE TITLE
CSS User history

### ISSUE THREAD

**Issue by elir0d** [roelisontrindade/FCC-Build-a-Personal-Portfolio-Webpage#2]
- [x] User Story #9: My portfolio should have at least one media query.

- [x] User Story #10: The height of the welcome section should be equal to the height of the viewport.

- [x] User Story #11: The navbar should always be at the top of the viewport.

- [x] Create a highlight color for the "a" tags
